"""added owner_id to reward class and updated seed data and def seed_rewards()

Revision ID: 28338b855807
Revises: ae2706875a0b
Create Date: 2024-02-19 12:21:36.889799

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '28338b855807'
down_revision = 'ae2706875a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('owner_id', 'users', ['owner_id'], ['id'])

    if environment == "production":
        op.execute(f"ALTER TABLE rewards SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_constraint('owner_id', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
